import React from "react";
import { BUILT_IN_RULES, ReviewPassId, REVIEW_PASS_IDS, ReviewSettings } from "../../../types";
import { ToggleSetting } from "./ToggleSetting";
import { EditableTextSetting } from "./EditableTextSetting";

interface Props {
  settings: ReviewSettings | undefined;
}

const PASS_LABELS: Record<ReviewPassId, string> = {
  security: "Security",
  bugs: "Bugs",
  performance: "Performance",
  style: "Style",
};

const QUALITY_CATEGORIES = [
  "Design & Architecture",
  "Code Clarity",
  "Error Handling",
  "Complexity & Simplicity",
  "Testability",
  "Production Readiness",
];

export function SettingsPage({ settings }: Props): React.JSX.Element {
  if (!settings) {
    return <p className="empty-state">Loading settings...</p>;
  }

  const activePassCount = REVIEW_PASS_IDS.filter((id) => settings.reviewPasses[id]).length;
  const activeRuleCount = BUILT_IN_RULES.filter((rule) => settings.builtInRules[rule.id]).length;

  return (
    <div className="settings-page">
      <section className="settings-section">
        <h3>Comment Format</h3>
        <p className="settings-section-description">
          Configure what information is included when comments are published to your Git provider.
        </p>
        <ToggleSetting
          settingKey="commentFormat.showSeverity"
          label="Show Severity"
          description="Include [LOW], [HIGH], etc. prefix in title"
          checked={settings.commentFormat.showSeverity}
        />
        <ToggleSetting
          settingKey="commentFormat.showCategory"
          label="Show Category"
          description='Include "Category: maintainability" line'
          checked={settings.commentFormat.showCategory}
        />
        <ToggleSetting
          settingKey="commentFormat.showFooter"
          label="Show Footer"
          description='Include "Generated by Bitbucket PR Reviewer" footer'
          checked={settings.commentFormat.showFooter}
        />
        <EditableTextSetting
          settingKey="commentFormat.template"
          title="Comment Template"
          description={
            <>
              Custom template for published comments. Use placeholders to insert review data. Leave empty for
              default format.
              <br />
              Available placeholders: <code>{"{severity}"}</code> <code>{"{title}"}</code>{" "}
              <code>{"{category}"}</code> <code>{"{description}"}</code> <code>{"{suggestion}"}</code>{" "}
              <code>{"{model}"}</code>
            </>
          }
          value={settings.commentFormat.template}
          rows={10}
          saveLabel="Save Template"
        />
      </section>

      <section className="settings-section">
        <h3>Review Prompt</h3>
        <p className="settings-section-description">
          Custom instructions added to every AI review request. Use this to customize review focus, coding
          standards, or project-specific rules.
        </p>
        <EditableTextSetting
          settingKey="reviewPrompt.custom"
          title=""
          value={settings.reviewPrompt}
          placeholder={
            "- Focus on security issues and potential vulnerabilities\n" +
            "- Check for proper error handling in async functions\n" +
            "- Ensure database queries use parameterized statements\n" +
            "- Look for performance issues and memory leaks\n" +
            "- Verify input validation and sanitization"
          }
          rows={8}
          saveLabel="Save Prompt"
        />
      </section>

      <section className="settings-section">
        <h3>Enhanced Security Scan</h3>
        <p className="settings-section-description">
          Run a specialized AI security analysis pass alongside the standard review. When disabled, the always-on
          security focus and regex rules still apply.
        </p>
        <ToggleSetting
          settingKey="enhancedSecurityScan.enabled"
          label="Enable Enhanced Security Scan"
          checked={settings.enhancedSecurityScan}
        />
      </section>

      <section className="settings-section">
        <h3>Specialized Review Passes</h3>
        <p className="settings-section-description">
          Enable expert-focused review passes. Each pass uses specialized prompts targeting specific issue types.{" "}
          <span className="settings-count">
            {activePassCount}/{REVIEW_PASS_IDS.length} active
          </span>
        </p>
        <div className="settings-toggle-row">
          {REVIEW_PASS_IDS.map((id) => (
            <ToggleSetting
              key={id}
              settingKey={`reviewPasses.${id}`}
              label={PASS_LABELS[id]}
              checked={settings.reviewPasses[id]}
            />
          ))}
        </div>

        {REVIEW_PASS_IDS.map((id) => (
          <EditableTextSetting
            key={id}
            settingKey={`passPrompts.${id}`}
            title={`${PASS_LABELS[id]} Prompt`}
            value={settings.passPrompts[id]}
            rows={12}
          />
        ))}
      </section>

      <section className="settings-section">
        <h3>Code Quality Assessment</h3>
        <p className="settings-section-description">
          AI scores your code across 6 categories (1-5 scale) with actionable recommendations.
        </p>
        <ul className="settings-quality-categories">
          {QUALITY_CATEGORIES.map((category) => (
            <li key={category}>{category}</li>
          ))}
        </ul>
        <EditableTextSetting
          settingKey="codeQuality.customPrompt"
          title="Custom quality prompt"
          value={settings.codeQuality.customPrompt}
          placeholder="e.g. Focus on SOLID principles and clean architecture"
          rows={4}
        />
      </section>

      <section className="settings-section">
        <h3>Excluded Files</h3>
        <p className="settings-section-description">
          Files matching these patterns are excluded from AI review. Lock files, generated code, and build outputs
          are excluded by default.
        </p>
        <EditableTextSetting
          settingKey="excludedFiles.customPatterns"
          title="Custom exclude patterns"
          description="One regex pattern per line, e.g.: vendor/, \.generated\.ts$, my-large-file\.json$"
          value={settings.excludedFiles.customPatterns}
          placeholder={"vendor/\n\\.generated\\.ts$\nmy-large-file\\.json$"}
          rows={6}
          saveLabel="Save Patterns"
          resetLabel="Clear"
        />
      </section>

      <section className="settings-section">
        <h3>File Review Rules</h3>
        <p className="settings-section-description">
          Control which files get a full AI review and which are skipped as trivial. PRs with only trivial files are
          skipped entirely.
        </p>
        <EditableTextSetting
          settingKey="fileRules.alwaysReview"
          title="Always review (full AI review)"
          description="These files always get reviewed, even if other rules say trivial. One regex per line."
          value={settings.fileRules.alwaysReview}
          placeholder={".github/workflows/\nDockerfile\nbitbucket-pipelines\\.yml"}
          rows={5}
          resetLabel="Clear"
        />
        <EditableTextSetting
          settingKey="fileRules.treatAsTrivial"
          title="Treat as trivial (skip review)"
          description="Additional patterns for files that should be classified as trivial. One regex per line."
          value={settings.fileRules.treatAsTrivial}
          placeholder={"\\.css$\nstyles/\nlocales/"}
          rows={5}
          resetLabel="Clear"
        />

        <h4 className="settings-subheading">
          Review Rules{" "}
          <span className="settings-count">
            {activeRuleCount}/{BUILT_IN_RULES.length} active
          </span>
        </h4>
        <div className="settings-rule-list">
          {BUILT_IN_RULES.map((rule) => (
            <ToggleSetting
              key={rule.id}
              settingKey={`builtInRules.${rule.id}`}
              label={rule.label}
              description={rule.pattern}
              checked={settings.builtInRules[rule.id]}
            />
          ))}
        </div>
      </section>
    </div>
  );
}
